return function(c)
  local h = {
    -- Editor UI
    Normal = { fg = c.fg, bg = c.bg },
    NormalNC = { fg = c.fg, bg = c.bg },
    NormalFloat = { fg = c.fg, bg = c.base1 },
    FloatBorder = { fg = c.base4, bg = c.base1 },
    FloatTitle = { fg = c.green, bg = c.base1, bold = true },
    Cursor = { reverse = true },
    lCursor = { link = "Cursor" },
    CursorIM = { link = "Cursor" },
    CursorLine = { bg = c.bg },
    CursorColumn = { bg = c.base0 },
    ColorColumn = { bg = c.base0 },
    LineNr = { fg = c.base3 },
    LineNrAbove = { fg = c.base3 },
    LineNrBelow = { fg = c.base3 },
    CursorLineNr = { fg = c.fg_alt },
    SignColumn = { fg = c.base4, bg = c.bg },
    FoldColumn = { fg = c.base4, bg = c.bg },
    Folded = { fg = c.comment, bg = c.base0 },
    NonText = { fg = c.base3 },
    EndOfBuffer = { fg = c.base3 },
    Whitespace = { fg = c.base3 },
    SpecialKey = { fg = c.base4 },
    Conceal = { fg = c.base5 },
    Visual = { bg = c.base3 },
    VisualNOS = { link = "Visual" },
    Search = { fg = c.bg, bg = c.yellow },
    CurSearch = { fg = c.bg, bg = c.orange },
    IncSearch = { fg = c.bg, bg = c.yellow },
    Substitute = { fg = c.bg, bg = c.red },
    MatchParen = { fg = c.fg, bg = c.base4, bold = true },
    Directory = { fg = c.blue, bold = true },
    Title = { fg = c.magenta, bold = true },
    ErrorMsg = { fg = c.red },
    WarningMsg = { fg = c.yellow },
    MoreMsg = { fg = c.green },
    Question = { fg = c.green },
    ModeMsg = { fg = c.fg_alt, bold = true },
    MsgArea = { fg = c.fg_alt },
    MsgSeparator = { fg = c.base4 },
    WinSeparator = { fg = c.base2, bg = c.bg },
    StatusLine = { fg = c.fg_alt, bg = c.bg },
    StatusLineNC = { fg = c.comment, bg = c.bg },
    TabLine = { fg = c.base4, bg = c.bg },
    TabLineSel = { fg = c.fg, bg = c.bg },
    TabLineFill = { bg = c.bg },
    WinBar = { fg = c.fg_alt, bg = c.bg, bold = true },
    WinBarNC = { fg = c.comment, bg = c.bg },
    Pmenu = { fg = c.fg_alt, bg = c.base1 },
    PmenuSel = { fg = c.fg, bg = c.base3, bold = true },
    PmenuKind = { fg = c.cyan, bg = c.base1 },
    PmenuKindSel = { fg = c.cyan, bg = c.base3 },
    PmenuExtra = { fg = c.comment, bg = c.base1 },
    PmenuExtraSel = { fg = c.fg_alt, bg = c.base3 },
    PmenuSbar = { bg = c.base2 },
    PmenuThumb = { bg = c.base5 },
    WildMenu = { link = "PmenuSel" },
    QuickFixLine = { bg = c.base3, bold = true },
    qfLineNr = { fg = c.yellow },

    -- Spellchecking
    SpellBad = { fg = c.bg, bg = c.magenta },
    SpellCap = { bg = c.yellow },
    SpellRare = { bg = c.cyan },
    SpellLocal = { bg = c.violet },

    -- Diff and version control
    DiffAdd = { fg = c.green, bg = c.diff_add },
    DiffChange = { fg = c.blue, bg = c.diff_change },
    DiffDelete = { fg = c.red, bg = c.diff_delete },
    DiffText = { fg = c.yellow, bg = c.diff_text, bold = true },
    Added = { fg = c.green },
    Changed = { fg = c.blue },
    Removed = { fg = c.red },
    GitSignsAdd = { fg = c.green },
    GitSignsChange = { fg = c.blue },
    GitSignsDelete = { fg = c.red },

    -- Legacy syntax groups
    Comment = { fg = c.comment },
    SpecialComment = { fg = c.yellow },
    Constant = { fg = c.violet },
    String = { fg = c.yellow },
    Character = { fg = c.yellow },
    Number = { fg = c.orange },
    Boolean = { fg = c.violet },
    Float = { fg = c.orange },
    Identifier = { fg = c.cyan },
    Function = { fg = c.green },
    Statement = { fg = c.magenta },
    Conditional = { link = "Statement" },
    Repeat = { link = "Statement" },
    Label = { link = "Statement" },
    Operator = { fg = c.cyan },
    Keyword = { fg = c.magenta },
    Exception = { link = "Keyword" },
    PreProc = { fg = c.blue },
    Include = { fg = c.magenta },
    Define = { fg = c.blue },
    Macro = { fg = c.blue },
    PreCondit = { link = "PreProc" },
    Type = { fg = c.cyan },
    StorageClass = { fg = c.magenta },
    Structure = { link = "Type" },
    Typedef = { link = "Type" },
    Special = { fg = c.blue },
    SpecialChar = { fg = c.cyan },
    Tag = { fg = c.red },
    Delimiter = { fg = c.fg_alt },
    Debug = { fg = c.red },
    Underlined = { fg = c.blue, underline = true },
    Ignore = { fg = c.comment },
    Error = { fg = c.red },
    Todo = { fg = c.bg, bg = c.yellow, bold = true },

    -- Tree-sitter captures
    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { fg = c.yellow },
    ["@comment.documentation.lua"] = { link = "Comment" },
    ["@comment.error"] = { fg = c.red, bold = true },
    ["@comment.warning"] = { fg = c.yellow, bold = true },
    ["@comment.todo"] = { link = "Todo" },
    ["@comment.note"] = { fg = c.blue, bold = true },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = c.blue },
    ["@constant.macro"] = { link = "Macro" },
    ["@module"] = { fg = c.orange },
    ["@module.builtin"] = { fg = c.blue },
    ["@string"] = { link = "String" },
    ["@string.documentation"] = { fg = c.yellow },
    ["@string.regexp"] = { fg = c.dark_cyan },
    ["@string.escape"] = { fg = c.cyan },
    ["@string.special"] = { fg = c.teal },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "SpecialChar" },
    ["@boolean"] = { link = "Boolean" },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = c.blue },
    ["@type.definition"] = { link = "Typedef" },
    ["@attribute"] = { fg = c.yellow, italic = true },
    ["@attribute.builtin"] = { fg = c.blue, italic = true },
    ["@property"] = { fg = c.yellow },
    ["@variable"] = { fg = c.cyan },
    ["@variable.builtin"] = { fg = c.blue },
    ["@variable.parameter"] = { fg = c.violet },
    ["@variable.parameter.builtin"] = { fg = c.blue },
    ["@variable.member"] = { fg = c.yellow },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { fg = c.blue },
    ["@function.call"] = { link = "Function" },
    ["@function.macro"] = { link = "Macro" },
    ["@function.method"] = { fg = c.blue },
    ["@function.method.call"] = { fg = c.blue },
    ["@constructor"] = { fg = c.blue },
    ["@operator"] = { link = "Operator" },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.coroutine"] = { link = "Keyword" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.operator"] = { link = "Keyword" },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.type"] = { link = "Keyword" },
    ["@keyword.modifier"] = { link = "Keyword" },
    ["@keyword.repeat"] = { link = "Repeat" },
    ["@keyword.return"] = { link = "Keyword" },
    ["@keyword.debug"] = { link = "Debug" },
    ["@keyword.exception"] = { link = "Exception" },
    ["@keyword.conditional"] = { link = "Conditional" },
    ["@keyword.conditional.ternary"] = { link = "Operator" },
    ["@keyword.directive"] = { link = "PreProc" },
    ["@keyword.directive.define"] = { link = "Define" },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { fg = c.base8 },
    ["@punctuation.special"] = { link = "Special" },
    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.heading"] = { fg = c.magenta, bold = true },
    ["@markup.quote"] = { fg = c.fg_alt, italic = true },
    ["@markup.math"] = { fg = c.violet },
    ["@markup.link"] = { fg = c.blue },
    ["@markup.link.label"] = { fg = c.cyan },
    ["@markup.link.url"] = { fg = c.blue, underline = true },
    ["@markup.raw"] = { fg = c.yellow, bg = c.base2 },
    ["@markup.raw.block"] = { fg = c.fg_alt, bg = c.base2 },
    ["@markup.list"] = { fg = c.magenta },
    ["@markup.list.checked"] = { fg = c.green },
    ["@markup.list.unchecked"] = { fg = c.base5 },
    ["@diff.plus"] = { link = "Added" },
    ["@diff.minus"] = { link = "Removed" },
    ["@diff.delta"] = { link = "Changed" },
    ["@tag"] = { fg = c.red },
    ["@tag.builtin"] = { fg = c.red },
    ["@tag.attribute"] = { fg = c.yellow, italic = true },
    ["@tag.delimiter"] = { fg = c.base8 },

    -- Language-specific
    ["@property.css"] = { fg = c.green },
    ["@type.css"] = { fg = c.blue },
    ["@variable.parameter.javascript"] = { fg = c.violet },
    ["@variable.parameter.typescript"] = { fg = c.violet },
    ["@variable.member.javascript"] = { fg = c.yellow },
    ["@variable.member.typescript"] = { fg = c.yellow },
    ["@tag.tsx"] = { fg = c.red },
    ["@tag.javascript"] = { fg = c.red },
    ["@tag.attribute.tsx"] = { fg = c.yellow, italic = true },
    markdownCode = { fg = c.fg_alt, bg = c.base2 },
    markdownCodeBlock = { fg = c.fg_alt, bg = c.base2 },

    -- Rainbow delimiters
    RainbowDelimiterRed = { fg = c.magenta },
    RainbowDelimiterOrange = { fg = c.orange },
    RainbowDelimiterYellow = { fg = c.yellow },
    RainbowDelimiterGreen = { fg = c.green },
    RainbowDelimiterCyan = { fg = c.cyan },
    RainbowDelimiterBlue = { fg = c.blue },
    RainbowDelimiterViolet = { fg = c.violet },

    -- Diagnostics and LSP
    DiagnosticError = { fg = c.red },
    DiagnosticWarn = { fg = c.yellow },
    DiagnosticInfo = { fg = c.blue },
    DiagnosticHint = { fg = c.cyan },
    DiagnosticOk = { fg = c.green },
    DiagnosticVirtualTextError = { fg = c.red, bg = c.base0 },
    DiagnosticVirtualTextWarn = { fg = c.yellow, bg = c.base0 },
    DiagnosticVirtualTextInfo = { fg = c.blue, bg = c.base0 },
    DiagnosticVirtualTextHint = { fg = c.cyan, bg = c.base0 },
    DiagnosticUnderlineError = { undercurl = true, sp = c.red },
    DiagnosticUnderlineWarn = { undercurl = true, sp = c.yellow },
    DiagnosticUnderlineInfo = { undercurl = true, sp = c.blue },
    DiagnosticUnderlineHint = { undercurl = true, sp = c.cyan },
    DiagnosticDeprecated = { strikethrough = true, sp = c.comment },
    DiagnosticUnnecessary = { fg = c.comment },
    LspReferenceText = { bg = c.base3 },
    LspReferenceRead = { bg = c.base3 },
    LspReferenceWrite = { bg = c.base3, bold = true },
    LspInlayHint = { fg = c.comment, bg = c.base0 },
    LspCodeLens = { fg = c.comment },
    LspCodeLensSeparator = { fg = c.base4 },
    LspSignatureActiveParameter = { fg = c.yellow, bold = true, underline = true },

    -- Plugin-specific
    TreesitterContext = { fg = c.fg, bg = "NONE" },
    TreesitterContextBottom = { underline = true, sp = c.base4 },
    TreesitterContextLineNumber = { fg = c.base3, bg = "NONE" },
    TreesitterContextLineNumberBottom = { fg = c.fg_alt, underline = true, sp = c.base4 },
    TreesitterContextSeparator = { link = "LineNr" },

    OilDir = { fg = c.blue, bold = true },
    OilDirHidden = { fg = c.base5 },
    OilDirIcon = { fg = c.blue },
    OilFileHidden = { fg = c.base5 },
    OilLink = { fg = c.cyan, underline = true },
    OilLinkTarget = { fg = c.comment },
    OilOrphanLink = { fg = c.red, underline = true },
    OilOrphanLinkTarget = { fg = c.red },
    OilSocket = { fg = c.violet },
    OilCreate = { fg = c.green },
    OilCopy = { fg = c.green },
    OilMove = { fg = c.yellow },
    OilChange = { fg = c.orange },
    OilDelete = { fg = c.red },
    OilPurge = { fg = c.red },
    OilRestore = { fg = c.green },
    OilTrash = { fg = c.orange },
    OilTrashSourcePath = { fg = c.comment },
    OilPreviewCursor = { link = "Visual" },
    OilVtext = { fg = c.comment },

    FzfLuaNormal = { link = "NormalFloat" },
    FzfLuaBorder = { link = "FloatBorder" },
    FzfLuaTitle = { link = "FloatTitle" },
    FzfLuaPreviewNormal = { link = "NormalFloat" },
    FzfLuaPreviewBorder = { link = "FloatBorder" },
    FzfLuaPreviewTitle = { fg = c.yellow, bg = c.base1, bold = true },
    FzfLuaCursorLine = { link = "PmenuSel" },
    FzfLuaCursorLineNr = { link = "CursorLineNr" },
    FzfLuaSearch = { link = "Search" },
    FzfLuaFzfMatch = { fg = c.yellow, bold = true },
    FzfLuaFzfPointer = { fg = c.magenta },
    FzfLuaFzfMarker = { fg = c.green },
    FzfLuaFzfPrompt = { fg = c.magenta },
    FzfLuaFzfSpinner = { fg = c.cyan },
    FzfLuaFzfInfo = { fg = c.comment },
    FzfLuaHeaderBind = { fg = c.green },
    FzfLuaHeaderText = { fg = c.yellow },
    FzfLuaPathColNr = { fg = c.violet },
    FzfLuaPathLineNr = { fg = c.yellow },
    FzfLuaDirPart = { fg = c.blue },
    FzfLuaFilePart = { fg = c.fg },
    FzfLuaBufFlagCur = { fg = c.green },
    FzfLuaBufFlagAlt = { fg = c.yellow },
    FzfLuaTabMarker = { fg = c.magenta },

    BlinkCmpMenu = { link = "Pmenu" },
    BlinkCmpMenuBorder = { link = "FloatBorder" },
    BlinkCmpMenuSelection = { link = "PmenuSel" },
    BlinkCmpLabel = { fg = c.fg_alt, bg = c.base1 },
    BlinkCmpLabelDeprecated = { fg = c.comment, bg = c.base1, strikethrough = true },
    BlinkCmpLabelMatch = { fg = c.yellow, bg = c.base1, bold = true },
    BlinkCmpLabelDetail = { link = "PmenuExtra" },
    BlinkCmpLabelDescription = { link = "PmenuExtra" },
    BlinkCmpKind = { link = "PmenuKind" },
    BlinkCmpSource = { link = "PmenuExtra" },
    BlinkCmpGhostText = { fg = c.base5 },
    BlinkCmpDoc = { link = "NormalFloat" },
    BlinkCmpDocBorder = { link = "FloatBorder" },
    BlinkCmpDocSeparator = { fg = c.base3, bg = c.base1 },
    BlinkCmpDocCursorLine = { link = "Visual" },
    BlinkCmpSignatureHelp = { link = "NormalFloat" },
    BlinkCmpSignatureHelpBorder = { link = "FloatBorder" },
    BlinkCmpSignatureHelpActiveParameter = { link = "LspSignatureActiveParameter" },

    AerialNormal = { link = "Normal" },
    AerialNormalFloat = { link = "NormalFloat" },
    AerialLine = { bg = c.base3 },
    AerialLineNC = { bg = c.base0 },
    AerialGuide = { fg = c.base3 },
    AerialPrivate = { fg = c.red },
    AerialProtected = { fg = c.yellow },
    AerialFlashHighlight = { link = "IncSearch" },

    FidgetTitle = { fg = c.green, bold = true },
    FidgetTask = { fg = c.comment },

    DapUINormal = { link = "Normal" },
    DapUIFloatNormal = { link = "NormalFloat" },
    DapUIFloatBorder = { link = "FloatBorder" },
    DapUIVariable = { fg = c.cyan },
    DapUIScope = { fg = c.magenta, bold = true },
    DapUIType = { fg = c.cyan },
    DapUIValue = { fg = c.fg_alt },
    DapUIModifiedValue = { fg = c.orange, bold = true },
    DapUIDecoration = { fg = c.blue },
    DapUIThread = { fg = c.blue },
    DapUIStoppedThread = { fg = c.green },
    DapUICurrentFrameName = { fg = c.green, bold = true },
    DapUISource = { fg = c.violet },
    DapUILineNumber = { link = "LineNr" },
    DapUIWatchesEmpty = { fg = c.comment },
    DapUIWatchesValue = { fg = c.green },
    DapUIWatchesError = { fg = c.red },
    DapUIBreakpointsPath = { fg = c.blue },
    DapUIBreakpointsInfo = { fg = c.green },
    DapUIBreakpointsCurrentLine = { fg = c.yellow, bold = true },
    DapUIBreakpointsDisabledLine = { fg = c.comment },
    DapUIStepOver = { fg = c.blue },
    DapUIStepInto = { fg = c.blue },
    DapUIStepBack = { fg = c.blue },
    DapUIStepOut = { fg = c.blue },
    DapUIStop = { fg = c.red },
    DapUIPlayPause = { fg = c.green },
    DapUIRestart = { fg = c.green },
    DapUIUnavailable = { fg = c.comment },
    DapUIWinSelect = { fg = c.yellow, bold = true },

    NERDTreeDir = { fg = c.blue },
    NERDTreeDirSlash = { fg = c.blue },
    NERDTreeOpenable = { fg = c.blue },
    NERDTreeClosable = { fg = c.blue },
    NERDTreeFile = { fg = c.fg_alt },
    NERDTreeExecFile = { fg = c.green },
    NERDTreeLinkFile = { fg = c.cyan },
    NERDTreeLinkDir = { fg = c.cyan },
    NERDTreeCWD = { fg = c.magenta, bold = true },
    NERDTreeHelp = { fg = c.comment },

    MasonHeader = { fg = c.bg, bg = c.magenta, bold = true },
    MasonHeaderSecondary = { fg = c.bg, bg = c.blue, bold = true },
    MasonHighlight = { fg = c.cyan },
    MasonHighlightSecondary = { fg = c.blue },
    MasonMuted = { fg = c.comment },
    MasonError = { fg = c.red },
    MasonWarning = { fg = c.yellow },
  }

  -- Aerial and completion both use LSP-style symbol kinds.
  local kinds = {
    Array = c.orange,
    Boolean = c.violet,
    Class = c.blue,
    Color = c.cyan,
    Constant = c.violet,
    Constructor = c.blue,
    Enum = c.cyan,
    EnumMember = c.violet,
    Event = c.magenta,
    Field = c.yellow,
    File = c.fg_alt,
    Folder = c.blue,
    Function = c.green,
    Interface = c.cyan,
    Key = c.yellow,
    Keyword = c.magenta,
    Method = c.blue,
    Module = c.orange,
    Namespace = c.orange,
    Null = c.violet,
    Number = c.orange,
    Object = c.cyan,
    Operator = c.cyan,
    Package = c.orange,
    Property = c.yellow,
    Reference = c.cyan,
    Snippet = c.green,
    String = c.yellow,
    Struct = c.cyan,
    Text = c.fg_alt,
    TypeParameter = c.cyan,
    Unit = c.orange,
    Value = c.orange,
    Variable = c.cyan,
  }

  for kind, color in pairs(kinds) do
    h["Aerial" .. kind .. "Icon"] = { fg = color }
    h["BlinkCmpKind" .. kind] = { fg = color, bg = c.base1 }
  end

  -- Included even though semantic tokens are currently disabled in init.lua,
  -- in case we need it later.
  local semantic_tokens = {
    boolean = "Boolean",
    class = "Type",
    comment = "Comment",
    decorator = "@attribute",
    enum = "Type",
    enumMember = "Constant",
    event = "Type",
    ["function"] = "Function",
    interface = "Type",
    keyword = "Keyword",
    macro = "Macro",
    method = "Function",
    modifier = "Keyword",
    namespace = "@module",
    number = "Number",
    operator = "Operator",
    parameter = "@variable.parameter",
    property = "@property",
    regexp = "@string.regexp",
    string = "String",
    struct = "Type",
    type = "Type",
    typeParameter = "Type",
    variable = "@variable",
  }

  for token, target in pairs(semantic_tokens) do
    h["@lsp.type." .. token] = { link = target }
  end

  return h
end
